services:

  migrate:
    build: .
    command: python manage.py migrate --noinput
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    restart: "no"

  app:
    build: .
    volumes:
      - '/mnt/storage/brightbean-media:/app/media'
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    ports:
      - '8095:8000'
    env_file:
      - .env
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  worker:
    build: .
    command: python manage.py process_tasks
    volumes:
      - /mnt/storage/brightbean-media:/app/media
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: brightbean
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
